[features]
seeds = true
skip-lint = false
[programs.devnet]
staking_program = "4VZBMgYfak2krLwYTw9LErqtHsvS3QL3m3kZr6jzWUic"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/adrou/Desktop/solana_stuff/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
