[features]
seeds = true
skip-lint = false
[programs.devnet]
staking_program = "9AdA14dP96xHcB4DMpJMYt1aRN46PuF74JXov7z3KCHU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/adrou/Desktop/solana_information/solana_keypair/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
